version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - npm i
  pre_build:
    commands:
    # - cp -r ./src/public ./
  build:
    commands:
      - npx prisma generate
      - npm run build
  post_build:
    commands:
      - ls -al
artifacts:
  files:
    - 'package*.json'
    - 'dist/**/*'
    - 'public/**/*'
    - 'views/**/*'
    - 'src/db/prisma/**/*'
    - '.ebextensions/**/*'
    - '.platform/**/*'
    - '.npmrc'
    - 'node_modules/**/*'
cache:
  paths:
    # - 'node_modules/**/*'
